books:
  Chest - Elicker - HRCT of the Lungs 2e.pdf:
    chapters: [49, 62, 83, 104, 116, 129, 150, 166, 174, 199, 212, 221, 233, 247,
      265, 274, 283, 296, 305]
    fonts: {text: [[Times-Roman, 9.5], [Times-Roman, 9.25], [Helvetica, 7.75]], head: [
        [Helvetica, 9.5], [Helvetica-Bold, 11.0]], bad: [[Helvetica, 7.0], [Helvetica,
          6.75]]}
  Chest - Felson - Principles of Chest Roentgenology (4e).pdf:
    chapters: [8, 29, 46, 68, 84, 104, 122, 136, 160, 182, 202, 226]
    fonts: {text: [], head: [], bad: [[Sabon, 10.0]]}
  Chest - Webb - Fundamentals of Body CT (4e).pdf:
    chapters: [6, 12, 26, 49, 73, 94, 134, 151, 176, 188, 214, 225, 241, 250, 278,
      290, 323, 340, 349, 363, 370]
    fonts: {head: [[Univers, 13.0], [Univers, 10.0]], text: [[JansonText, 10.0], [
          AGYLNO+Univers, 8.0]], bad: [[OKZFDQ+Helvetica, 8.0], [JansonText, 8.0]]}
  General - Brant _ Helms - Fundamentals of Diagnostic Radiology (4e).pdf:
    chapters: [12, 38, 334, 546, 578, 628, 680, 806, 868, 990, 1138, 1238, 1418]
  General - Mandell - Core Radiology (1e).pdf:
    chapters: [12, 98, 168, 212, 357, 475, 564, 603, 669, 705, 752, 849, 874]
  General - Weissleder - Primer of Diagnostic Imaging (5e).pdf:
    chapters: [13, 84, 127, 216, 280, 365, 439, 474, 521, 545, 587, 649, 692, 702,
      759]
    detectron:
      pdfplumber: true
      box_pad: 0.050
    fonts: {head: [ Univers, 18.0 ], text: [[ Garamond, 10.0 ], [Univers, 9.5]], bad: [ [CFWYQT+Univers, 8.0] ]}
  test:
    chapters: [-1, -1]
    fonts: {head: [[ HeadFont, 2.0 ]], text: [[ TextFont, 1.0 ]], bad: [[ BadFont, 3.0 ]]}
base:
  detectron:
    model_name: "lp://PubLayNet/mask_rcnn_X_101_32x8d_FPN_3x/config"
    score_co: 0.70
    box_pad: 0.010
    resolution: 150
  tokens:
    fontbreak: '[FONTBREAK]'
    label_end: '[LABEL_END]'
    nofont: '[NOFONT]'
    startup: '[STARTUP]'
  cleaning:
    hyphen:
      extras:
      - Three-dimensional
      - Multiple-detector
      - Two-and
      - Multiple-detector
      - four-detector-row
      - Post-expiratory
      - soft-tissue
      - two-or
      - arrowhead-shaped
      - fat-filled
      - short-axis
      - out-flow
      - mirror-image
      - left-sided
      - Contrast-enhanced
      - post-traumatic
      - x-rays
      - medullary-based
      - MDCT-guided
      - volume-rendered
      - volume-rendering
      - contrast-opacified
      - thick-walled
      - thin-walled
      - bolus-contrast-enhanced
      - Contrast-filled
      - smooth-outlined
      - sheet-like
      - small-bowel
      - Colon-wall
      - tumor-involved
      - Early-stage
      - Closed-loop
      - B-cell
      - Mucosa-associated
      - three-layer
      - region-of-interest
      - lipid-rich
      - Lipid-poor
      - non-Hodgkin
      - fat-containing
      - bone-marrow
      - Thin-section
      - Axial-plane
      - sagittal-plane
      - well-hydrated
      - end-stage
      - image-guided
      - fluid-filled
      - non-neoplastic
      - hairline-thin
      - well-marginated
      - Lymphad-enectomy
      - Nephron-sparing
      - mid-T-12
      - CT-KUB
      - CT-IVP
      - water-density
      - bunch-of-grapes
      - main-duct
      - branch-duct
      - duct-obstructing
      - AIDS-related
      - Hormone-producing
      - ultrasound-guided
      - Long-segment
      - upper-quadrant
      - IV-A
      - IV-B
      - tech-netium-99m-labeled
      - technetium-99m
      - delayed-phase
      - Well-differentiated
      - venous-phase
      - arterial-phase
      - arterial-phase
      - nodule-in-nodule
      - False-positive
      - comma-shaped
      - 2*-weighted
      - video-assisted
      prefixs:
      - high
      - higher
      - highest
      suffixs:
      - mm
      - cm
      - m
